### PR TITLE
Update docs action (and update the docs a smidge)

### PR DESCRIPTION
**Pull request by werebus**
This is mostly to see if #155 works, but it turns out I _did_ find a tiny typo.

### CODE REVIEW

**Comment by werebus** [comment]
#155 did _not_, in fact, work. But I fiddled with it on this branch for a bit (hence the force-push) and now it does.

**Review by benmelz — APPROVED** [review]

**Comment by werebus** [comment]
0b86c132dfcd22632a44d77f28f22c62

**Comment by werebus** [comment]
Pushing to `main` doesn't work because, well, we don't allow pushing to `main`.

**Comment by benmelz** [comment]
I was considering suggesting this on the original PR, but what about pushing to PR branches as a part of CI?

I guess a big downside would be having to remember to `git pull` if you want to add more stuff

**Comment by werebus** [comment]
Sure seems like we "should", but I can't find the option anywhere in the branch protection settings.

**Pull request merged**
